### PR TITLE
Update js/bootstrap-notify.js

### PR DESCRIPTION
**Pull request by rubenstolk**
Code readability solving jslint issues.

### CODE REVIEW

**Comment by nijikokun** [comment]
You can disable specific jslint monitoring through a header, I think I will do this, as those changes break foundational javascript guidelines that I strictly follow

**Comment by rubenstolk** [comment]
Well, I can't imagine that declaring variables as global is recommended according to any javascript guidelines!

Then, what you're doing on line 47-50 doesn't make sense either, you've indented the code like 49 and 50 belong in the closure started on 47, still you don't use curly braces so the code is really mangled.

I think you might be talking about Python guidelines :)

**Comment by nijikokun** [comment]
I can agree on the globals, but indentions, I don't like curly braces and avoid them when possible, it is a feature of the language and intend to use it as much as possible. even when I do curly braces, never newline.

I take that back, that section has not been fully expound upon yet, but never newline else if braces like so:

``` js
}
else (if logic if applicable) {
```

**Comment by rubenstolk** [comment]
Thanks, I'm not against any code guideline, but I'm against code that breaks!

**Comment by nijikokun** [comment]
I have updated the lines, removed globals, and cleaned it up a bit.

**Comment by rubenstolk** [comment]
And now you made a typo... perhaps we should get your code tested...

**Comment by nijikokun** [comment]
Where at? I don't see it...

**Comment by rubenstolk** [comment]
Ya, line 56. Never mind, I'm going to make a fork, have some more changes like actually using fn.notify.defaults.fadeOut.delay...

**Comment by nijikokun** [comment]
There are tests btw, it's just a gh-pages branch, which I'm updating now, and the typo has been fixed.

**Comment by rubenstolk** [comment]
Cool, thanks!

**Comment by nijikokun** [comment]
No problem mate

**Pull request closed without merging**
